spring:
  application:
    name: listable-storage

storage:
  bucket-name: listable-bucket

services:
  repo: https://listable-repo.appspot.com/api

management:
  security:
    enabled: false

debug: false

